const path = require('node:path')
const { exec } = require('node:child_process');

const autogeneratedTypesFilePath = path.join(__dirname, '../src', 'generated-types.ts');

const scriptDir = __dirname;
const rootDir = path.join(scriptDir, '../../..');

const cmdCommand =
  `go run ${rootDir}/nil/cmd/ts_generate/main.go -o ${autogeneratedTypesFilePath}`;

exec(cmdCommand, (error, stdout, stderr) => {
  if (error) {
    console.error(`exec error: ${error}`);
    return;
  };

  console.log(`stdout: ${stdout}`);
  console.error(`stderr: ${stderr}`);
});
